DROP TABLE IF EXISTS tiles;
DROP TABLE IF EXISTS labels;
DROP TABLE IF EXISTS slides;
DROP TABLE IF EXISTS tile_labels;

CREATE TABLE slides (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slide_name TEXT NOT NULL UNIQUE
);

CREATE TABLE tiles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slide_id INTEGER NOT NULL,
  coords TEXT NOT NULL,
  FOREIGN KEY (slide_id) REFERENCES slides (id)
);

CREATE TABLE labels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  label TEXT UNIQUE
);

CREATE TABLE tile_labels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tile_id INTEGER NOT NULL,
  label_id INTEGER NOT NULL,
  FOREIGN KEY (tile_id) REFERENCES tiles (id),
  FOREIGN KEY (label_id) REFERENCES labels (id)
);