DROP TABLE IF EXISTS tile;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS slides;
DROP TABLE IF EXISTS tileComments;

CREATE TABLE slides (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slide_name TEXT
);

CREATE TABLE tiles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slide_id INTEGER NOT NULL,
  coords INTEGER NOT NULL,
  label TEXT,
  FOREIGN KEY (slide_id) REFERENCES slides (id)
);